### ISSUE TITLE
Properly document arguments of runemjmcmc

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/EMJMCMC2016#10]
>    Undocumented arguments in documentation object 'runemjmcmc'
>     ‘latnames’ ‘p.add.default’ ‘save.beta’ ‘deep.method’
>   Documented arguments not in \usage in documentation object 'runemjmcmc':
>     ‘o.add.default’﻿

**Comment by wleoncio** [comment]
Hi @aliaksah,

Could you help me by adding a description to the following arguments of `runemjmcmc()`?

- [x] `latnames`
- [ ] `p.add.default`
- [x] `save.beta`
- [x] `deep.method`

I couldn't find these in the manual.

Additionally, there's one argument on the manual, `o.add.default`, which not used in the code. If that is not used anymore I can just drop it; its reads "a parameter defining sparcity after filtrations in gmjmcmc as initial marginal inclusion probabilities vector for paramters in the current pool".

BTW, the CRAN-candidate version of the package is under development on the [develop](https://github.com/ocbe-uio/EMJMCMC/tree/develop) branch, in case you wanna check it out.

Cheers,
Waldir

**Comment by aliaksah** [comment]
Thank you, Waldir


I will look into that after the meeting with my student,


Aliaksandr


________________________________
