### ISSUE TITLE
Describe arguments in `estimate.gamma.cpen*`

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/EMJMCMC2016#24]
In preparation of issue #23, particularly when reworking the examples, it looks like it's better to export `estimate.gamma.cpen()` and `estimate.gamma.cpen_2()` (IIRC you've also mentioned this export as being beneficial to the user, so win-win).

The functions are partially documented, we just need to properly describe the parameters and add a `@return` entry with the returned object. See below:

https://github.com/ocbe-uio/EMJMCMC/blob/0b26de13deeb10601236f8d71313b07e81152074/R/estimate.gamma.cpen.R#L1-L7

@aliaksah, could you help me with the parameter descriptions? We only need to do it once for `cpen`, as `cpen_2` inherits the parameters from the former. I'll add the `@return` and `@export` tags now, so I can keep working on the examples.

**Comment by wleoncio** [comment]
Actually, it may be good to improve the `@title` and add a `@description`, while we're at it. :)

**Comment by aliaksah** [comment]
Dear Waldir,

Thank you! Will do later tonight,

Aliaksandr

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Waldir Leoncio ***@***.***>
Sent: Thursday, April 25, 2024 11:27:48 AM
To: ocbe-uio/EMJMCMC ***@***.***>
Cc: Aliaksandr Hubin ***@***.***>; Mention ***@***.***>
Subject: [ocbe-uio/EMJMCMC] Describe arguments in `estimate.gamma.cpen*` (Issue #24)


In preparation of issue #23<https://github.com/ocbe-uio/EMJMCMC/issues/23>, particularly when reworking the examples, it looks like it's better to export estimate.gamma.cpen() and estimate.gamma.cpen_2() (IIRC you've also mentioned this export as being beneficial to the user, so win-win).

The functions are partially documented, we just need to properly describe the parameters and add a @return entry with the returned object. See below:

https://github.com/ocbe-uio/EMJMCMC/blob/0b26de13deeb10601236f8d71313b07e81152074/R/estimate.gamma.cpen.R#L1-L7

@aliaksah<https://github.com/aliaksah>, could you help me with the parameter descriptions? We only need to do it once for cpen, as cpen_2 inherits the parameters from the former. I'll add the @return and @export tags now, so I can keep working on the examples.

**Comment by wleoncio** [comment]
Closed by 109e8e5
